name: wafflebrowny
favicon: null
layout_spectrum: 0.96481
typography_spectrum: 0.48601
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
